server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth
              uri: ${auth.service.url}
              predicates:
                - Path=/auth/**
              filters:
                - name: JwtAuthFilter

            - id: todo
              uri: ${todo.service.url}
              predicates:
                - Path=/todo/**
              filters:
                - name: JwtAuthFilter

            - id: notify
              uri: ${notify.service.url}
              predicates:
                - Path=/notify/**
              filters:
                - name: JwtAuthFilter

jwt:
  secret: ${jwt.secret}

management:
  endpoints:
    web:
      exposure:
        include: health,info