spring:
  datasource:
    url: jdbc:mysql://localhost:3309/notify_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

rabbit:
  exchanges:
    auth: "auth.exchange"
    todo: "todo.exchange"
  deadline:
    queue:
      name: "todo.deadline.queue"
      key: "todo.deadline.key"
  reminder:
    queue:
      name: "todo.reminder.queue"
      key: "todo.reminder.key"