name: Deploy auth Services to HomeServer

on:
  push:
    branches:
      - main
    paths:
      - "auth/**"
  workflow_dispatch:

permissions:
  contents: read

env:
  DOCKERHUB_NAMESPACE: shinhs6384
  IMAGE_TAG: ${{ github.sha }}
  HOME_HOST: ${{ secrets.HOME_HOST }}
  HOME_USER: ${{ secrets.HOME_USER }}
  HOME_PASSWORD: ${{ secrets.HOME_PASSWORD }}

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push auth image
        run : |
          docker build -f auth/Dockerfile -t ${{ env.DOCKERHUB_NAMESPACE }}/auth:${{ env.IMAGE_TAG }} auth
          docker push ${{ env.DOCKERHUB_NAMESPACE }}/auth:${{ env.IMAGE_TAG }}
          docker tag ${{ env.DOCKERHUB_NAMESPACE }}/auth:${{ env.IMAGE_TAG }} ${{ env.DOCKERHUB_NAMESPACE }}/auth:latest
          docker push ${{ env.DOCKERHUB_NAMESPACE }}/auth:latest

  deploy:
    name: Deploy to HomeServer
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH into HomeServer and run deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ env.HOME_HOST }}
          port: 4242
          username: ${{ env.HOME_USER }}
          password: ${{ env.HOME_PASSWORD }}
          script: |
            cd /home/hyeongsh/betterlife
            docker compose -p betterlife -f docker-compose.service.yml pull auth
            docker compose -p betterlife -f docker-compose.service.yml up -d auth